insert into counties (id, district_id, name) values (0101, 1, 'Águeda');
insert into counties (id, district_id, name) values (0102, 1, 'Albergaria-a-Velha');
insert into counties (id, district_id, name) values (0103, 1, 'Anadia');
insert into counties (id, district_id, name) values (0104, 1, 'Arouca');
insert into counties (id, district_id, name) values (0105, 1, 'Aveiro');
insert into counties (id, district_id, name) values (0106, 1, 'Castelo de Paiva');
insert into counties (id, district_id, name) values (0107, 1, 'Espinho');
insert into counties (id, district_id, name) values (0108, 1, 'Estarreja');
insert into counties (id, district_id, name) values (0109, 1, 'Santa Maria da Feira');
insert into counties (id, district_id, name) values (0110, 1, 'Ílhavo');
insert into counties (id, district_id, name) values (0111, 1, 'Mealhada');
insert into counties (id, district_id, name) values (0112, 1, 'Murtosa');
insert into counties (id, district_id, name) values (0113, 1, 'Oliveira de Azeméis');
insert into counties (id, district_id, name) values (0114, 1, 'Oliveira do Bairro');
insert into counties (id, district_id, name) values (0115, 1, 'Ovar');
insert into counties (id, district_id, name) values (0116, 1, 'São João da Madeira');
insert into counties (id, district_id, name) values (0117, 1, 'Sever do Vouga');
insert into counties (id, district_id, name) values (0118, 1, 'Vagos');
insert into counties (id, district_id, name) values (0119, 1, 'Vale de Cambra');
insert into counties (id, district_id, name) values (0201, 2, 'Aljustrel');
insert into counties (id, district_id, name) values (0202, 2, 'Almodóvar');
insert into counties (id, district_id, name) values (0203, 2, 'Alvito');
insert into counties (id, district_id, name) values (0204, 2, 'Barrancos');
insert into counties (id, district_id, name) values (0205, 2, 'Beja');
insert into counties (id, district_id, name) values (0206, 2, 'Castro Verde');
insert into counties (id, district_id, name) values (0207, 2, 'Cuba');
insert into counties (id, district_id, name) values (0208, 2, 'Ferreira do Alentejo');
insert into counties (id, district_id, name) values (0209, 2, 'Mértola');
insert into counties (id, district_id, name) values (0210, 2, 'Moura');
insert into counties (id, district_id, name) values (0211, 2, 'Odemira');
insert into counties (id, district_id, name) values (0212, 2, 'Ourique');
insert into counties (id, district_id, name) values (0213, 2, 'Serpa');
insert into counties (id, district_id, name) values (0214, 2, 'Vidigueira');
insert into counties (id, district_id, name) values (0301, 3, 'Amares');
insert into counties (id, district_id, name) values (0302, 3, 'Barcelos');
insert into counties (id, district_id, name) values (0303, 3, 'Braga');
insert into counties (id, district_id, name) values (0304, 3, 'Cabeceiras de Basto');
insert into counties (id, district_id, name) values (0305, 3, 'Celorico de Basto');
insert into counties (id, district_id, name) values (0306, 3, 'Esposende');
insert into counties (id, district_id, name) values (0307, 3, 'Fafe');
insert into counties (id, district_id, name) values (0308, 3, 'Guimarães');
insert into counties (id, district_id, name) values (0309, 3, 'Póvoa de Lanhoso');
insert into counties (id, district_id, name) values (0310, 3, 'Terras de Bouro');
insert into counties (id, district_id, name) values (0311, 3, 'Vieira do Minho');
insert into counties (id, district_id, name) values (0312, 3, 'Vila Nova de Famalicão');
insert into counties (id, district_id, name) values (0313, 3, 'Vila Verde');
insert into counties (id, district_id, name) values (0314, 3, 'Vizela');
insert into counties (id, district_id, name) values (0401, 4, 'Alfândega da Fé');
insert into counties (id, district_id, name) values (0402, 4, 'Bragança');
insert into counties (id, district_id, name) values (0403, 4, 'Carrazeda de Ansiães');
insert into counties (id, district_id, name) values (0404, 4, 'Freixo de Espada à Cinta');
insert into counties (id, district_id, name) values (0405, 4, 'Macedo de Cavaleiros');
insert into counties (id, district_id, name) values (0406, 4, 'Miranda do Douro');
insert into counties (id, district_id, name) values (0407, 4, 'Mirandela');
insert into counties (id, district_id, name) values (0408, 4, 'Mogadouro');
insert into counties (id, district_id, name) values (0409, 4, 'Torre de Moncorvo');
insert into counties (id, district_id, name) values (0410, 4, 'Vila Flor');
insert into counties (id, district_id, name) values (0411, 4, 'Vimioso');
insert into counties (id, district_id, name) values (0412, 4, 'Vinhais');
insert into counties (id, district_id, name) values (0501, 5, 'Belmonte');
insert into counties (id, district_id, name) values (0502, 5, 'Castelo Branco');
insert into counties (id, district_id, name) values (0503, 5, 'Covilhã');
insert into counties (id, district_id, name) values (0504, 5, 'Fundão');
insert into counties (id, district_id, name) values (0505, 5, 'Idanha-a-Nova');
insert into counties (id, district_id, name) values (0506, 5, 'Oleiros');
insert into counties (id, district_id, name) values (0507, 5, 'Penamacor');
insert into counties (id, district_id, name) values (0508, 5, 'Proença-a-Nova');
insert into counties (id, district_id, name) values (0509, 5, 'Sertã');
insert into counties (id, district_id, name) values (0510, 5, 'Vila de Rei');
insert into counties (id, district_id, name) values (0511, 5, 'Vila Velha de Rodão');
insert into counties (id, district_id, name) values (0601, 6, 'Arganil');
insert into counties (id, district_id, name) values (0602, 6, 'Cantanhede');
insert into counties (id, district_id, name) values (0603, 6, 'Coimbra');
insert into counties (id, district_id, name) values (0604, 6, 'Condeixa-a-Nova');
insert into counties (id, district_id, name) values (0605, 6, 'Figueira da Foz');
insert into counties (id, district_id, name) values (0606, 6, 'Góis');
insert into counties (id, district_id, name) values (0607, 6, 'Lousã');
insert into counties (id, district_id, name) values (0608, 6, 'Mira');
insert into counties (id, district_id, name) values (0609, 6, 'Miranda do Corvo');
insert into counties (id, district_id, name) values (0610, 6, 'Montemor-o-Velho');
insert into counties (id, district_id, name) values (0611, 6, 'Oliveira do Hospital');
insert into counties (id, district_id, name) values (0612, 6, 'Pampilhosa da Serra');
insert into counties (id, district_id, name) values (0613, 6, 'Penacova');
insert into counties (id, district_id, name) values (0614, 6, 'Penela');
insert into counties (id, district_id, name) values (0615, 6, 'Soure');
insert into counties (id, district_id, name) values (0616, 6, 'Tábua');
insert into counties (id, district_id, name) values (0617, 6, 'Vila Nova de Poiares');
insert into counties (id, district_id, name) values (0701, 7, 'Alandroal');
insert into counties (id, district_id, name) values (0702, 7, 'Arraiolos');
insert into counties (id, district_id, name) values (0703, 7, 'Borba');
insert into counties (id, district_id, name) values (0704, 7, 'Estremoz');
insert into counties (id, district_id, name) values (0705, 7, 'Évora');
insert into counties (id, district_id, name) values (0706, 7, 'Montemor-o-Novo');
insert into counties (id, district_id, name) values (0707, 7, 'Mora');
insert into counties (id, district_id, name) values (0708, 7, 'Mourão');
insert into counties (id, district_id, name) values (0709, 7, 'Portel');
insert into counties (id, district_id, name) values (0710, 7, 'Redondo');
insert into counties (id, district_id, name) values (0711, 7, 'Reguengos de Monsaraz');
insert into counties (id, district_id, name) values (0712, 7, 'Vendas Novas');
insert into counties (id, district_id, name) values (0713, 7, 'Viana do Alentejo');
insert into counties (id, district_id, name) values (0714, 7, 'Vila Viçosa');
insert into counties (id, district_id, name) values (0801, 8, 'Albufeira');
insert into counties (id, district_id, name) values (0802, 8, 'Alcoutim');
insert into counties (id, district_id, name) values (0803, 8, 'Aljezur');
insert into counties (id, district_id, name) values (0804, 8, 'Castro Marim');
insert into counties (id, district_id, name) values (0805, 8, 'Faro');
insert into counties (id, district_id, name) values (0806, 8, 'Lagoa');
insert into counties (id, district_id, name) values (0807, 8, 'Lagos');
insert into counties (id, district_id, name) values (0808, 8, 'Loulé');
insert into counties (id, district_id, name) values (0809, 8, 'Monchique');
insert into counties (id, district_id, name) values (0810, 8, 'Olhão');
insert into counties (id, district_id, name) values (0811, 8, 'Portimão');
insert into counties (id, district_id, name) values (0812, 8, 'São Brás de Alportel');
insert into counties (id, district_id, name) values (0813, 8, 'Silves');
insert into counties (id, district_id, name) values (0814, 8, 'Tavira');
insert into counties (id, district_id, name) values (0815, 8, 'Vila do Bispo');
insert into counties (id, district_id, name) values (0816, 8, 'Vila Real de Santo António');
insert into counties (id, district_id, name) values (0901, 9, 'Aguiar da Beira');
insert into counties (id, district_id, name) values (0902, 9, 'Almeida');
insert into counties (id, district_id, name) values (0903, 9, 'Celorico da Beira');
insert into counties (id, district_id, name) values (0904, 9, 'Figueira de Castelo Rodrigo');
insert into counties (id, district_id, name) values (0905, 9, 'Fornos de Algodres');
insert into counties (id, district_id, name) values (0906, 9, 'Gouveia');
insert into counties (id, district_id, name) values (0907, 9, 'Guarda');
insert into counties (id, district_id, name) values (0908, 9, 'Manteigas');
insert into counties (id, district_id, name) values (0909, 9, 'Mêda');
insert into counties (id, district_id, name) values (0910, 9, 'Pinhel');
insert into counties (id, district_id, name) values (0911, 9, 'Sabugal');
insert into counties (id, district_id, name) values (0912, 9, 'Seia');
insert into counties (id, district_id, name) values (0913, 9, 'Trancoso');
insert into counties (id, district_id, name) values (0914, 9, 'Vila Nova de Foz Cóa');
insert into counties (id, district_id, name) values (1001, 10, 'Alcobaça');
insert into counties (id, district_id, name) values (1002, 10, 'Alvaiázere');
insert into counties (id, district_id, name) values (1003, 10, 'Ansião');
insert into counties (id, district_id, name) values (1004, 10, 'Batalha');
insert into counties (id, district_id, name) values (1005, 10, 'Bombarral');
insert into counties (id, district_id, name) values (1006, 10, 'Caldas da Rainha');
insert into counties (id, district_id, name) values (1007, 10, 'Castanheira de Pêra');
insert into counties (id, district_id, name) values (1008, 10, 'Figueiró dos Vinhos');
insert into counties (id, district_id, name) values (1009, 10, 'Leiria');
insert into counties (id, district_id, name) values (1010, 10, 'Marinha Grande');
insert into counties (id, district_id, name) values (1011, 10, 'Nazaré');
insert into counties (id, district_id, name) values (1012, 10, 'Óbidos');
insert into counties (id, district_id, name) values (1013, 10, 'Pedrógão Grande');
insert into counties (id, district_id, name) values (1014, 10, 'Peniche');
insert into counties (id, district_id, name) values (1015, 10, 'Pombal');
insert into counties (id, district_id, name) values (1016, 10, 'Porto de Mós');
insert into counties (id, district_id, name) values (1101, 11, 'Alenquer');
insert into counties (id, district_id, name) values (1102, 11, 'Arruda dos Vinhos');
insert into counties (id, district_id, name) values (1103, 11, 'Azambuja');
insert into counties (id, district_id, name) values (1104, 11, 'Cadaval');
insert into counties (id, district_id, name) values (1105, 11, 'Cascais');
insert into counties (id, district_id, name) values (1106, 11, 'Lisboa');
insert into counties (id, district_id, name) values (1107, 11, 'Loures');
insert into counties (id, district_id, name) values (1108, 11, 'Lourinhã');
insert into counties (id, district_id, name) values (1109, 11, 'Mafra');
insert into counties (id, district_id, name) values (1110, 11, 'Oeiras');
insert into counties (id, district_id, name) values (1111, 11, 'Sintra');
insert into counties (id, district_id, name) values (1112, 11, 'Sobral de Monte Agraço');
insert into counties (id, district_id, name) values (1113, 11, 'Torres Vedras');
insert into counties (id, district_id, name) values (1114, 11, 'Vila Franca de Xira');
insert into counties (id, district_id, name) values (1115, 11, 'Amadora');
insert into counties (id, district_id, name) values (1116, 11, 'Odivelas');
insert into counties (id, district_id, name) values (1201, 12, 'Alter do Chão');
insert into counties (id, district_id, name) values (1202, 12, 'Arronches');
insert into counties (id, district_id, name) values (1203, 12, 'Avis');
insert into counties (id, district_id, name) values (1204, 12, 'Campo Maior');
insert into counties (id, district_id, name) values (1205, 12, 'Castelo de Vide');
insert into counties (id, district_id, name) values (1206, 12, 'Crato');
insert into counties (id, district_id, name) values (1207, 12, 'Elvas');
insert into counties (id, district_id, name) values (1208, 12, 'Fronteira');
insert into counties (id, district_id, name) values (1209, 12, 'Gavião');
insert into counties (id, district_id, name) values (1210, 12, 'Marvão');
insert into counties (id, district_id, name) values (1211, 12, 'Monforte');
insert into counties (id, district_id, name) values (1212, 12, 'Nisa');
insert into counties (id, district_id, name) values (1213, 12, 'Ponte de Sor');
insert into counties (id, district_id, name) values (1214, 12, 'Portalegre');
insert into counties (id, district_id, name) values (1215, 12, 'Sousel');
insert into counties (id, district_id, name) values (1301, 13, 'Amarante');
insert into counties (id, district_id, name) values (1302, 13, 'Baião');
insert into counties (id, district_id, name) values (1303, 13, 'Felgueiras');
insert into counties (id, district_id, name) values (1304, 13, 'Gondomar');
insert into counties (id, district_id, name) values (1305, 13, 'Lousada');
insert into counties (id, district_id, name) values (1306, 13, 'Maia');
insert into counties (id, district_id, name) values (1307, 13, 'Marco de Canaveses');
insert into counties (id, district_id, name) values (1308, 13, 'Matosinhos');
insert into counties (id, district_id, name) values (1309, 13, 'Paços de Ferreira');
insert into counties (id, district_id, name) values (1310, 13, 'Paredes');
insert into counties (id, district_id, name) values (1311, 13, 'Penafiel');
insert into counties (id, district_id, name) values (1312, 13, 'Porto');
insert into counties (id, district_id, name) values (1313, 13, 'Póvoa de Varzim');
insert into counties (id, district_id, name) values (1314, 13, 'Santo Tirso');
insert into counties (id, district_id, name) values (1315, 13, 'Valongo');
insert into counties (id, district_id, name) values (1316, 13, 'Vila do Conde');
insert into counties (id, district_id, name) values (1317, 13, 'Vila Nova de Gaia');
insert into counties (id, district_id, name) values (1318, 13, 'Trofa');
insert into counties (id, district_id, name) values (1401, 14, 'Abrantes');
insert into counties (id, district_id, name) values (1402, 14, 'Alcanena');
insert into counties (id, district_id, name) values (1403, 14, 'Almeirim');
insert into counties (id, district_id, name) values (1404, 14, 'Alpiarça');
insert into counties (id, district_id, name) values (1405, 14, 'Benavente');
insert into counties (id, district_id, name) values (1406, 14, 'Cartaxo');
insert into counties (id, district_id, name) values (1407, 14, 'Chamusca');
insert into counties (id, district_id, name) values (1408, 14, 'Constância');
insert into counties (id, district_id, name) values (1409, 14, 'Coruche');
insert into counties (id, district_id, name) values (1410, 14, 'Entroncamento');
insert into counties (id, district_id, name) values (1411, 14, 'Ferreira do Zézere');
insert into counties (id, district_id, name) values (1412, 14, 'Golegã');
insert into counties (id, district_id, name) values (1413, 14, 'Mação');
insert into counties (id, district_id, name) values (1414, 14, 'Rio Maior');
insert into counties (id, district_id, name) values (1415, 14, 'Salvaterra de Magos');
insert into counties (id, district_id, name) values (1416, 14, 'Santarém');
insert into counties (id, district_id, name) values (1417, 14, 'Sardoal');
insert into counties (id, district_id, name) values (1418, 14, 'Tomar');
insert into counties (id, district_id, name) values (1419, 14, 'Torres Novas');
insert into counties (id, district_id, name) values (1420, 14, 'Vila Nova da Barquinha');
insert into counties (id, district_id, name) values (1421, 14, 'Ourém');
insert into counties (id, district_id, name) values (1501, 15, 'Alcácer do Sal');
insert into counties (id, district_id, name) values (1502, 15, 'Alcochete');
insert into counties (id, district_id, name) values (1503, 15, 'Almada');
insert into counties (id, district_id, name) values (1504, 15, 'Barreiro');
insert into counties (id, district_id, name) values (1505, 15, 'Grândola');
insert into counties (id, district_id, name) values (1506, 15, 'Moita');
insert into counties (id, district_id, name) values (1507, 15, 'Montijo');
insert into counties (id, district_id, name) values (1508, 15, 'Palmela');
insert into counties (id, district_id, name) values (1509, 15, 'Santiago do Cacém');
insert into counties (id, district_id, name) values (1510, 15, 'Seixal');
insert into counties (id, district_id, name) values (1511, 15, 'Sesimbra');
insert into counties (id, district_id, name) values (1512, 15, 'Setúbal');
insert into counties (id, district_id, name) values (1513, 15, 'Sines');
insert into counties (id, district_id, name) values (1601, 16, 'Arcos de Valdevez');
insert into counties (id, district_id, name) values (1602, 16, 'Caminha');
insert into counties (id, district_id, name) values (1603, 16, 'Melgaço');
insert into counties (id, district_id, name) values (1604, 16, 'Monção');
insert into counties (id, district_id, name) values (1605, 16, 'Paredes de Coura');
insert into counties (id, district_id, name) values (1606, 16, 'Ponte da Barca');
insert into counties (id, district_id, name) values (1607, 16, 'Ponte de Lima');
insert into counties (id, district_id, name) values (1608, 16, 'Valença');
insert into counties (id, district_id, name) values (1609, 16, 'Viana do Castelo');
insert into counties (id, district_id, name) values (1610, 16, 'Vila Nova de Cerveira');
insert into counties (id, district_id, name) values (1701, 17, 'Alijó');
insert into counties (id, district_id, name) values (1702, 17, 'Boticas');
insert into counties (id, district_id, name) values (1703, 17, 'Chaves');
insert into counties (id, district_id, name) values (1704, 17, 'Mesão Frio');
insert into counties (id, district_id, name) values (1705, 17, 'Mondim de Basto');
insert into counties (id, district_id, name) values (1706, 17, 'Montalegre');
insert into counties (id, district_id, name) values (1707, 17, 'Murça');
insert into counties (id, district_id, name) values (1708, 17, 'Peso da Régua');
insert into counties (id, district_id, name) values (1709, 17, 'Ribeira de Pena');
insert into counties (id, district_id, name) values (1710, 17, 'Sabrosa');
insert into counties (id, district_id, name) values (1711, 17, 'Santa Marta de Penaguião');
insert into counties (id, district_id, name) values (1712, 17, 'Valpaços');
insert into counties (id, district_id, name) values (1713, 17, 'Vila Pouca de Aguiar');
insert into counties (id, district_id, name) values (1714, 17, 'Vila Real');
insert into counties (id, district_id, name) values (1801, 18, 'Armamar');
insert into counties (id, district_id, name) values (1802, 18, 'Carregal do Sal');
insert into counties (id, district_id, name) values (1803, 18, 'Castro Daire');
insert into counties (id, district_id, name) values (1804, 18, 'Cinfães');
insert into counties (id, district_id, name) values (1805, 18, 'Lamego');
insert into counties (id, district_id, name) values (1806, 18, 'Mangualde');
insert into counties (id, district_id, name) values (1807, 18, 'Moimenta da Beira');
insert into counties (id, district_id, name) values (1808, 18, 'Mortágua');
insert into counties (id, district_id, name) values (1809, 18, 'Nelas');
insert into counties (id, district_id, name) values (1810, 18, 'Oliveira de Frades');
insert into counties (id, district_id, name) values (1811, 18, 'Penalva do Castelo');
insert into counties (id, district_id, name) values (1812, 18, 'Penedono');
insert into counties (id, district_id, name) values (1813, 18, 'Resende');
insert into counties (id, district_id, name) values (1814, 18, 'Santa Comba Dão');
insert into counties (id, district_id, name) values (1815, 18, 'São João da Pesqueira');
insert into counties (id, district_id, name) values (1816, 18, 'São Pedro do Sul');
insert into counties (id, district_id, name) values (1817, 18, 'Sátão');
insert into counties (id, district_id, name) values (1818, 18, 'Sernancelhe');
insert into counties (id, district_id, name) values (1819, 18, 'Tabuaço');
insert into counties (id, district_id, name) values (1820, 18, 'Tarouca');
insert into counties (id, district_id, name) values (1821, 18, 'Tondela');
insert into counties (id, district_id, name) values (1822, 18, 'Vila Nova de Paiva');
insert into counties (id, district_id, name) values (1823, 18, 'Viseu');
insert into counties (id, district_id, name) values (1824, 18, 'Vouzela');
insert into counties (id, district_id, name) values (3101, 31, 'Calheta');
insert into counties (id, district_id, name) values (3102, 31, 'Câmara de Lobos');
insert into counties (id, district_id, name) values (3103, 31, 'Funchal');
insert into counties (id, district_id, name) values (3104, 31, 'Machico');
insert into counties (id, district_id, name) values (3105, 31, 'Ponta do Sol');
insert into counties (id, district_id, name) values (3106, 31, 'Porto Moniz');
insert into counties (id, district_id, name) values (3107, 31, 'Ribeira Brava');
insert into counties (id, district_id, name) values (3108, 31, 'Santa Cruz');
insert into counties (id, district_id, name) values (3109, 31, 'Santana');
insert into counties (id, district_id, name) values (3110, 31, 'São Vicente');
insert into counties (id, district_id, name) values (3201, 32, 'Porto Santo');
insert into counties (id, district_id, name) values (4101, 41, 'Vila do Porto');
insert into counties (id, district_id, name) values (4201, 42, 'Lagoa');
insert into counties (id, district_id, name) values (4202, 42, 'Nordeste');
insert into counties (id, district_id, name) values (4203, 42, 'Ponta Delgada');
insert into counties (id, district_id, name) values (4204, 42, 'Povoação');
insert into counties (id, district_id, name) values (4205, 42, 'Ribeira Grande');
insert into counties (id, district_id, name) values (4206, 42, 'Vila Franca do Campo');
insert into counties (id, district_id, name) values (4301, 43, 'Angra do Heroísmo');
insert into counties (id, district_id, name) values (4302, 43, 'Vila da Praia da Vitória');
insert into counties (id, district_id, name) values (4401, 44, 'Santa Cruz da Graciosa');
insert into counties (id, district_id, name) values (4501, 45, 'Calheta');
insert into counties (id, district_id, name) values (4502, 45, 'Velas');
insert into counties (id, district_id, name) values (4601, 46, 'Lajes do Pico');
insert into counties (id, district_id, name) values (4602, 46, 'Madalena');
insert into counties (id, district_id, name) values (4603, 46, 'São Roque do Pico');
insert into counties (id, district_id, name) values (4701, 47, 'Horta');
insert into counties (id, district_id, name) values (4801, 48, 'Lajes das Flores');
insert into counties (id, district_id, name) values (4802, 48, 'Santa Cruz das Flores');
insert into counties (id, district_id, name) values (4901, 49, 'Corvo');
