insert into districts (id, name) values (1, 'Aveiro');
insert into districts (id, name) values (2, 'Beja');
insert into districts (id, name) values (3, 'Braga');
insert into districts (id, name) values (4, 'Bragança');
insert into districts (id, name) values (5, 'Castelo Branco');
insert into districts (id, name) values (6, 'Coimbra');
insert into districts (id, name) values (7, 'Évora');
insert into districts (id, name) values (8, 'Faro');
insert into districts (id, name) values (9, 'Guarda');
insert into districts (id, name) values (10, 'Leiria');
insert into districts (id, name) values (11, 'Lisboa');
insert into districts (id, name) values (12, 'Portalegre');
insert into districts (id, name) values (13, 'Porto');
insert into districts (id, name) values (14, 'Santarém');
insert into districts (id, name) values (15, 'Setúbal');
insert into districts (id, name) values (16, 'Viana do Castelo');
insert into districts (id, name) values (17, 'Vila Real');
insert into districts (id, name) values (18, 'Viseu');
insert into districts (id, name) values (31, 'Ilha da Madeira');
insert into districts (id, name) values (32, 'Ilha de Porto Santo');
insert into districts (id, name) values (41, 'Ilha de Santa Maria');
insert into districts (id, name) values (42, 'Ilha de São Miguel');
insert into districts (id, name) values (43, 'Ilha Terceira');
insert into districts (id, name) values (44, 'Ilha Graciosa');
insert into districts (id, name) values (45, 'Ilha de São Jorge');
insert into districts (id, name) values (46, 'Ilha do Pico');
insert into districts (id, name) values (47, 'Ilha do Faial');
insert into districts (id, name) values (48, 'Ilha das Flores');
insert into districts (id, name) values (49, 'Ilha do Corvo');